apiVersion: v1
kind: Service
metadata:
  name: pygoat-service
spec:
  selector:
    app: pygoat
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000          
      targetPort: 8000    
      nodePort: 32383     


