apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygoat-deployment
  labels:
    app: pygoat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pygoat
  template:
    metadata:
      labels:
        app: pygoat
    spec:
      containers:
        - name: pygoat
          image: leberi/pygoat:latest
          imagePullPolicy: Always



          


