name: PyGoat

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: lint terraform files
        uses: terraform-linters/setup-tflint@v4
        with:
          version: v0.47.0
      - name: check terraform file 
        run: |
          cd EKS-Terraform
          tflint 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: terraform fmt
        run: |
          cd EKS-Terraform
          terraform fmt -check 

      - name: terraform validate
        run: |
          cd EKS-Terraform
          terraform init 
          terraform validate 

      - name: install kube-linter
        run: |
          curl -s https://raw.githubusercontent.com/stackrox/kube-linter/main/install.sh | bash
          sudo mv kube-linter /usr/local/bin/
      
      - name: lint kubernetes manifests
        run: kube-linter lint ./manifests


  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: installer docker et docker compose
        run: | 
          chmod +x scripts/docker_install.sh
          ./scripts/docker_install.sh

      - name: Test my app
        run: | 
          docker build -t pygoat-test .
          docker run pygoat-test pytest
          docker ps -a 
          docker rm $(docker ps -a -q)


  
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: installer docker et docker compose
        run: | 
          chmod +x scripts/docker_install.sh
          ./scripts/docker_install.sh

      - name: Build my app
        run: | 
          docker build -t pygoat-prod .
      
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push to docker hub
        run: | 
          docker push pygoat-prod:latest 


  

